version: "3.7"
services:
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'inventory-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    volumes:
      - ./my-db:/var/lib/mysql
    networks:
      - mercado-network
  product-info:
    build:
      dockerfile: Dockerfile
      context: ./product-information-management-system
    ports:
      - "8080:8080"
    networks:
      - mercado-network
    depends_on:
      - mysql-db
  product-sync:
    build:
      dockerfile: Dockerfile
      context: ./product-synchronizer
    ports:
      - "8081:8081"
    volumes:
      - ./data:/app/data
    networks:
      - mercado-network
    depends_on:
      - mysql-db
      - product-info

networks:
  mercado-network: {}
