server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql-db:3306/inventory-db?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  batch:
    job:
      enabled: false
    initialize-schema: always


product:
  url:
    bulk:
      upload: http://product-info:8080/api/v1/products/bulk

  data:
    file:
      path: /app/data/products-data.csv


  upload:
    job:
      execution:
        frequency: 0 0/1 * * * ?


