server:
  port: 8081

spring:
  batch:
    job:
      enabled: false

product:
  url:
    bulk:
      upload: http://localhost:8080/api/v1/products/bulk

  data:
    file:
      path: /data/products-data.csv


  upload:
    job:
      execution:
        frequency: 0 0/30 * * * ?
